### PR TITLE
Update DSL tests

### PR DESCRIPTION
**Pull request by sahuang**
Since Milvus only supports one single vector in a collection, float and binary schema should be tested separately.

### CODE REVIEW

**Comment by sahuang** [comment]
I am also concerned about the current usage:

'''java
Query floatVectorQuery(List<List<Float>> floatVectors) {
    return bool(
        must(
            schema.intField.gt(5).lte(10),
            schema.floatVectorField.query(vectors).param("nprobe", 16).top(1)));
}
'''

If the user does not predefine a schema, then this method cannot be used. Also it is not very clear that `.gt(5).lte(10)` represents a range query.

I originally [planned](https://github.com/milvus-io/milvus/issues/3401) to implement the DSL query builder similar to [Elastic Search](https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.9/java-compound-queries.html), where the definition is something like:

'''java
boolQuery()
        .must(termQuery("int64", "x"))                 
        .must(rangeQuery("float")                                             
                      .gte("10")                                                
                      .lt("20"))                 
        .mustNot(vectorQuery("vec_float", "y"))
'''

**Comment by sahuang** [comment]
I am also concerned about the current usage:

```java
Query floatVectorQuery(List<List<Float>> floatVectors) {
    return bool(
        must(
            schema.intField.gt(5).lte(10),
            schema.floatVectorField.query(vectors).param("nprobe", 16).top(1)));
}
```

If the user does not predefine a schema, then this method cannot be used. Also it is not very clear that `.gt(5).lte(10)` represents a range query.

I originally [planned](https://github.com/milvus-io/milvus/issues/3401) to implement the DSL query builder similar to [Elastic Search](https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.9/java-compound-queries.html), where the definition is something like:

```java
boolQuery()
    .must(termQuery("int64", "x"))                 
    .must(rangeQuery("float").gte("10").lt("20"))                 
    .mustNot(vectorQuery("vec_float", "y"))
```

**Comment by thirstycrow** [comment]
> If the user does not predefine a schema, then this method cannot be used. 

The MilvusService API was designed to enforce consistency and type safety. I think it worth the cost to define a schema in project development. It's not meant for interactive use. For that purpose, scripting languages would be a better choice.

> Also it is not very clear that `.gt(5).lte(10)` represents a range query.

As a user, all I care about is what conditions an individual field should satisfy and how the conditions compose. How the variety of conditions are categorised does not help. So why I have to learn it to build queries?

**Comment by sahuang** [comment]
You are right, I think the current design is indeed preferred over specifying query type.

**Pull request merged**
